//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace БДНИЛ_Учёт__деятельности_лабаратории
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public int IdProvider { get; set; }
        public string NameOfSupplier { get; set; }
        public int ResourceId { get; set; }
        public Nullable<int> AccountSupplierId { get; set; }
        public int AdressId1 { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual BankProvider BankProvider { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
